In [100]:
from sklearn import tree
import pandas as pd
import os

In [101]:
df = pd.read_csv('Nba_injuries_small.csv')
df.head()

,Position,BMI,Strains/Sprains_y_True,Dislocations_y_True,Arm Fractures_y_True,Leg Fractures_y_True
0,G,24.391892,0,0,0,0
1,C,25.188615,0,0,0,0
2,F-C,26.660470,1,0,0,0
3,F,22.528441,0,0,0,0
4,F-C,26.532153,0,0,0,0

In [102]:
pos_labels = {}
for idx, row in df.iterrows():
    if row["Position"] not in pos_labels:
        pos_labels[row["Position"]] = len(pos_labels)
print(pos_labels)

{'G': 0, 'C': 1, 'F-C': 2, 'F': 3, 'F-G': 4}

In [103]:
for pos in pos_labels:
    df.replace(pos, pos_labels[pos], inplace=True)
df.head()

,Position,BMI,Strains/Sprains_y_True,Dislocations_y_True,Arm Fractures_y_True,Leg Fractures_y_True
0,0,24.391892,0,0,0,0
1,1,25.188615,0,0,0,0
2,2,26.660470,1,0,0,0
3,3,22.528441,0,0,0,0
4,2,26.532153,0,0,0,0

In [104]:
data = df.values
X = data[:, 0:2]
y = data[:, 2:6]

In [105]:
print(X)

[[ 0.         24.39189189]
 [ 1.         25.18861547]
 [ 2.         26.66046996]
 [ 3.         22.52844095]
 [ 2.         26.53215271]
 [ 0.         26.67819194]
 [ 0.         23.47680891]
 [ 1.         24.18507766]
 [ 0.         24.99555556]
 [ 3.         23.57262612]
 [ 4.         26.57626561]
 [ 3.         24.64410913]
 [ 3.         25.09220702]
 [ 3.         24.69531137]
 [ 3.         20.91017252]
 [ 3.         25.48375   ]
 [ 0.         24.99555556]
 [ 3.         23.61640625]
 [ 0.         24.81655093]
 [ 1.         24.32525952]
 [ 4.         24.89392726]
 [ 3.         23.87893744]
 [ 0.         21.95430638]
 [ 1.         22.01856576]
 [ 0.         25.08777006]
 [ 3.         24.71484375]
 [ 0.         21.95430638]
 [ 3.         24.53696083]
 [ 4.         21.96875   ]
 [ 0.         24.99555556]
 [ 2.         27.18322427]
 [ 0.         23.83251813]
 [ 0.         24.54393658]
 [ 0.         23.12109968]
 [ 4.         24.89964581]
 [ 3.         24.00121933]
 [ 3.         24.265286  ]
 [ 3.         21.89273356]
 [ 0.         24.34210526]
 [ 3.         23.52394408]
 [ 0.         24.40514168]
 [ 1.         24.96555403]
 [ 1.         27.32281664]
 [ 3.         24.46490184]
 [ 0.         23.36842105]
 [ 0.         27.04353537]
 [ 3.         24.165625  ]
 [ 4.         22.87869822]
 [ 0.         23.68754109]
 [ 3.         23.72625   ]
 [ 1.         25.90419501]
 [ 3.         23.00118977]
 [ 0.         19.771875  ]
 [ 0.         24.265286  ]
 [ 3.         20.91017252]
 [ 0.         23.10810811]
 [ 1.         25.92861392]
 [ 4.         19.9295839 ]
 [ 3.         23.654863  ]
 [ 3.         25.34449607]
 [ 4.         24.21807403]
 [ 0.         27.15247091]
 [ 4.         25.42077581]
 [ 3.         24.21807403]
 [ 0.         23.95108787]
 [ 0.         24.78128505]
 [ 0.         26.80736358]
 [ 0.         23.74577778]
 [ 1.         25.30759181]
 [ 4.         23.09165198]
 [ 0.         23.08594483]
 [ 0.         24.72748192]
 [ 0.         28.45673807]
 [ 4.         25.48375   ]
 [ 3.         23.35832952]
 [ 0.         24.99555556]
 [ 0.         24.3067971 ]
 [ 1.         25.09220702]
 [ 3.         23.61640625]
 [ 0.         25.16216216]
 [ 4.         25.42077581]
 [ 1.         26.66046996]
 [ 0.         21.95430638]
 [ 0.         22.053972  ]
 [ 1.         23.91156463]
 [ 0.         25.55921053]
 [ 3.         25.50129553]
 [ 1.         23.35224913]
 [ 3.         24.10836763]
 [ 0.         23.74577778]
 [ 0.         23.73167438]
 [ 3.         25.09220702]
 [ 3.         24.71484375]
 [ 0.         21.87111111]
 [ 0.         23.00252994]
 [ 2.         24.56945271]
 [ 2.         23.98098418]
 [ 0.         23.73167438]
 [ 3.         25.99852071]
 [ 0.         23.08594483]
 [ 0.         25.4375    ]
 [ 0.          2.43918919]
 [ 2.         27.55262012]
 [ 3.         24.10836763]
 [ 3.         24.49638396]
 [ 3.         25.49249452]
 [ 0.         23.12088889]
 [ 4.         27.38486842]
 [ 3.         28.60197368]
 [ 3.         26.57626561]
 [ 0.         25.08777006]
 [ 0.         23.74577778]
 [ 0.         24.95065789]
 [ 2.         26.45136823]
 [ 2.         24.18507766]
 [ 1.         23.52394408]
 [ 0.         24.78128505]
 [ 1.         24.40972222]
 [ 3.         24.64410913]
 [ 1.         25.61496133]
 [ 0.         24.34210526]
 [ 3.         25.39414723]
 [ 3.         28.77169625]
 [ 0.         24.70723684]
 [ 3.         23.57262612]
 [ 0.         23.47680891]
 [ 3.         25.71577878]
 [ 0.         24.265286  ]
 [ 4.         24.55600064]
 [ 0.         21.69826278]
 [ 0.         24.265286  ]
 [ 4.         23.68754109]
 [ 0.         23.74577778]
 [ 1.         28.47104079]
 [ 3.         26.69620253]
 [ 0.         24.95065789]
 [ 3.         25.71559214]
 [ 0.         24.26351351]
 [ 3.         24.71484375]
 [ 3.         25.61496133]
 [ 0.         23.71394839]
 [ 1.         24.90787982]
 [ 3.         23.654863  ]
 [ 3.         25.61496133]
 [ 0.         24.265286  ]
 [ 0.         25.7658179 ]
 [ 0.         21.95430638]
 [ 2.         24.165625  ]
 [ 3.         27.70597858]
 [ 2.         27.70597858]
 [ 0.         27.04353537]
 [ 0.         21.40201891]
 [ 0.         24.40972222]
 [ 3.         24.165625  ]
 [ 0.         23.74577778]
 [ 4.         23.09165198]
 [ 0.         21.87111111]
 [ 0.         24.34210526]
 [ 0.         22.42634641]
 [ 4.         23.10979619]
 [ 0.         25.03378378]
 [ 0.         24.34210526]
 [ 3.         21.96540162]
 [ 3.         23.52394408]
 [ 0.         25.67567568]
 [ 4.         24.8430309 ]
 [ 1.         24.81176471]
 [ 2.         24.90787982]
 [ 3.         25.2640625 ]
 [ 3.         23.57262612]
 [ 0.         23.75      ]
 [ 3.         24.85840573]
 [ 2.         25.09220702]
 [ 0.         20.91436555]
 [ 1.         23.83875433]
 [ 0.         23.10810811]
 [ 3.         23.57262612]
 [ 0.         26.16776316]
 [ 0.         23.75      ]
 [ 3.         26.67819194]
 [ 3.         23.57262612]
 [ 0.         24.95065789]
 [ 3.         23.61640625]
 [ 4.         24.8430309 ]
 [ 2.         25.9077071 ]
 [ 4.         23.09165198]
 [ 3.         24.32266423]
 [ 3.         25.17985063]
 [ 3.         26.13771565]
 [ 4.         23.68754109]
 [ 0.         26.08534323]
 [ 3.         23.57262612]
 [ 3.         26.3625    ]
 [ 0.         23.12088889]
 [ 0.         25.55921053]
 [ 4.         25.18967784]
 [ 3.         25.17985063]
 [ 0.         23.125     ]
 [ 2.         24.8082483 ]
 [ 0.         25.49249452]
 [ 3.         23.61640625]
 [ 3.         24.71484375]
 [ 3.         22.34823632]
 [ 3.         25.2640625 ]
 [ 1.         24.49121788]
 [ 3.         24.71484375]
 [ 3.         24.64410913]
 [ 0.         26.04605263]
 [ 3.         24.78128505]
 [ 0.         23.49582222]
 [ 3.         25.34449607]
 [ 0.         24.40514168]
 [ 0.         24.95065789]
 [ 4.         20.91436555]
 [ 3.         24.44335844]
 [ 2.         24.56945271]
 [ 0.         22.6278125 ]
 [ 2.         25.61496133]
 [ 4.         24.78128505]
 [ 1.         27.04238641]
 [ 0.         21.40201891]
 [ 1.         25.90419501]
 [ 0.         21.93540226]
 [ 3.         22.19051434]
 [ 3.         24.56945271]
 [ 3.         24.8430309 ]
 [ 3.         24.56945271]
 [ 3.         24.8246875 ]
 [ 3.         20.35817711]
 [ 0.         24.12071111]
 [ 3.         21.95568114]
 [ 3.         21.96522993]
 [ 2.         24.69531137]
 [ 0.         25.62044444]
 [ 3.         21.96875   ]
 [ 3.         23.0671875 ]
 [ 0.         25.99537778]
 [ 3.         27.4609375 ]
 [ 3.         23.78692273]
 [ 0.         26.16776316]
 [ 3.         24.15124926]
 [ 3.         23.286875  ]
 [ 2.         25.71559214]
 [ 3.         23.10979619]
 [ 3.         26.3625    ]
 [ 3.         27.59734017]
 [ 0.         23.125     ]
 [ 4.         24.21807403]
 [ 1.         24.90787982]
 [ 4.         22.52844095]
 [ 1.         24.40972222]
 [ 3.         20.6311351 ]
 [ 0.         25.16216216]
 [ 1.         27.04238641]
 [ 0.         24.12071111]
 [ 2.         24.11082766]
 [ 1.         25.5116853 ]
 [ 3.         24.42536684]
 [ 3.         26.13299151]
 [ 3.         25.42077581]
 [ 3.         24.49121788]
 [ 0.         24.37066667]
 [ 3.         23.03688462]
 [ 4.         21.40201891]
 [ 2.         24.32525952]
 [ 4.         23.88014741]
 [ 1.         24.40972222]
 [ 3.         19.50455807]
 [ 3.         23.57262612]
 [ 3.         23.98098418]
 [ 0.         21.93540226]
 [ 0.         23.71394839]
 [ 3.         23.03688462]
 [ 3.         23.52394408]
 [ 0.         21.94004935]
 [ 0.         24.265286  ]
 [ 0.         22.496     ]
 [ 1.         24.32525952]
 [ 2.         24.81176471]
 [ 3.         23.83759667]
 [ 0.         22.97900977]
 [ 0.         24.37066667]
 [ 0.         24.99555556]
 [ 0.         21.62730332]
 [ 2.         23.57262612]
 [ 1.         26.9005102 ]
 [ 1.         27.3986678 ]
 [ 2.         26.24226651]
 [ 0.         25.85625821]
 [ 0.         25.55921053]
 [ 0.         25.72433853]
 [ 4.         24.265286  ]
 [ 3.         23.52394408]
 [ 3.         24.46490184]
 [ 0.         25.37048889]
 [ 0.         23.12088889]
 [ 0.         24.3067971 ]
 [ 1.         26.73624619]
 [ 3.         21.50352941]
 [ 1.         26.9348659 ]
 [ 3.         23.91156463]
 [ 3.         24.98765616]
 [ 0.         26.49672684]
 [ 3.         26.3625    ]
 [ 4.         26.08534323]
 [ 0.         20.83880788]
 [ 0.         23.74577778]
 [ 0.         24.39189189]
 [ 3.         24.71484375]
 [ 1.         26.9005102 ]
 [ 4.         24.34210526]
 [ 3.         23.61640625]
 [ 0.         21.22398381]
 [ 0.         25.55921053]
 [ 1.         22.33707409]
 [ 0.         24.34210526]
 [ 3.         23.52394408]
 [ 3.         24.3853125 ]
 [ 4.         25.42077581]
 [ 3.         24.71484375]
 [ 3.         23.654863  ]
 [ 3.         27.0215625 ]
 [ 0.         24.40972222]
 [ 0.         23.91863905]
 [ 3.         26.13771565]
 [ 0.         26.87022222]
 [ 0.         26.53289474]
 [ 0.         24.99555556]
 [ 1.         27.04238641]
 [ 3.         24.165625  ]
 [ 0.         23.24671053]
 [ 2.         24.88310529]
 [ 3.         25.17985063]
 [ 3.         25.61496133]
 [ 0.         21.87111111]
 [ 2.         21.91893424]
 [ 3.         24.04669839]
 [ 1.         26.75778547]
 [ 0.         23.71394839]
 [ 0.         20.15685613]
 [ 0.         25.19407895]
 [ 4.         22.28684652]
 [ 2.         24.49121788]
 [ 0.         22.51796875]
 [ 3.         25.99852071]
 [ 3.         24.64410913]
 [ 0.         23.74554325]
 [ 2.         25.5116853 ]
 [ 0.         23.61362357]
 [ 3.         25.2640625 ]
 [ 1.         23.47075047]
 [ 2.         22.45028306]
 [ 0.         23.10979619]
 [ 0.         22.99591111]
 [ 1.         27.3986678 ]
 [ 0.         26.65460526]
 [ 3.         26.11406969]
 [ 1.         26.13771565]
 [ 3.         27.14677135]
 [ 1.         28.06285382]
 [ 0.         23.74577778]
 [ 0.         25.80263158]
 [ 0.         25.55921053]
 [ 3.         23.91156463]
 [ 3.         23.61640625]
 [ 3.         23.09165198]
 [ 1.         27.55262012]
 [ 3.         26.91171875]
 [ 3.         24.04669839]
 [ 3.         24.64410913]
 [ 0.         23.73167438]
 [ 0.         22.51644737]
 [ 0.         24.37066667]
 [ 4.         25.18967784]
 [ 2.         23.98098418]
 [ 1.         25.40963855]
 [ 1.         22.91524943]
 [ 3.         25.9077071 ]
 [ 3.         21.95568114]
 [ 3.         21.7490625 ]
 [ 3.         25.5116853 ]
 [ 2.         22.2909235 ]
 [ 2.         24.49121788]
 [ 4.         26.16776316]
 [ 3.         25.17985063]
 [ 3.         24.165625  ]
 [ 3.         23.00118977]
 [ 0.         23.75      ]
 [ 2.         26.78707514]
 [ 0.         24.34210526]
 [ 0.         24.66250632]
 [ 0.         24.71484375]
 [ 4.         23.10979619]
 [ 0.         24.34210526]
 [ 4.         23.654863  ]
 [ 4.         25.65187377]
 [ 3.         21.96875   ]
 [ 3.         23.0671875 ]
 [ 0.         22.52825097]
 [ 1.         23.35224913]
 [ 0.         24.53706136]
 [ 0.         24.99555556]
 [ 4.         23.20429418]
 [ 0.         25.0647401 ]
 [ 0.         23.125     ]
 [ 0.         23.47680891]
 [ 3.         24.49121788]
 [ 0.         21.81683252]
 [ 3.         23.31484236]
 [ 4.         23.654863  ]
 [ 0.         22.69018578]
 [ 3.         26.03296875]
 [ 3.         24.78128505]
 [ 4.         27.27104065]
 [ 0.         24.39189189]
 [ 0.         22.29111149]
 [ 0.         25.49249452]
 [ 3.         24.64410913]
 [ 4.         24.04669839]
 [ 3.         22.53205128]
 [ 0.         22.51644737]
 [ 0.         26.77631579]
 [ 0.         24.37066667]
 [ 0.         23.73167438]
 [ 4.         25.99852071]
 [ 0.         24.22039474]
 [ 0.         23.99278962]
 [ 3.         22.47843546]
 [ 3.         26.25133364]
 [ 0.         23.68754109]
 [ 0.         26.57626561]
 [ 0.         20.33662064]
 [ 3.         26.78707514]
 [ 3.         22.8475    ]
 [ 0.         25.03378378]
 [ 4.         22.53205128]
 [ 0.         28.36995556]
 [ 3.         26.69203125]
 [ 0.         27.31674018]
 [ 0.         26.24533333]
 [ 3.         26.3625    ]
 [ 0.         24.21807403]
 [ 2.         24.88310529]
 [ 0.         25.49249452]
 [ 3.         27.4609375 ]
 [ 1.         24.70861678]
 [ 0.         23.68754109]
 [ 0.         23.71394839]
 [ 3.         28.30950033]
 [ 4.         24.78128505]
 [ 2.         25.5116853 ]
 [ 2.         25.61496133]
 [ 1.         26.40235261]
 [ 0.         24.265286  ]
 [ 3.         22.92973632]
 [ 0.         26.44386574]
 [ 3.         26.78707514]
 [ 1.         25.90419501]
 [ 1.         25.00145159]
 [ 0.         26.16776316]
 [ 0.         24.3067971 ]
 [ 0.         24.27322199]
 [ 0.         23.47680891]
 [ 0.         25.55921053]
 [ 0.         25.55921053]
 [ 3.         23.61640625]
 [ 4.         22.95734375]
 [ 0.         21.96540162]
 [ 1.         25.40603741]
 [ 0.         24.99555556]
 [ 0.         23.125     ]
 [ 0.         25.92434211]
 [ 1.         26.40235261]
 [ 4.         21.3096875 ]
 [ 2.         25.09220702]
 [ 2.         29.10859375]
 [ 0.         26.79676168]
 [ 3.         24.42981253]
 [ 4.         23.654863  ]
 [ 0.         23.08594483]
 [ 3.         25.39414723]
 [ 3.         24.55600064]
 [ 3.         24.15124926]
 [ 4.         25.34449607]
 [ 3.         22.37388459]
 [ 0.         21.69826278]
 [ 3.         28.559375  ]
 [ 3.         24.27546875]
 [ 0.         23.10810811]
 [ 1.         23.91156463]
 [ 1.         25.20677438]
 [ 1.         25.91987226]
 [ 1.         23.35224913]]

In [106]:
spraintarget = df["Strains/Sprains_y_True"]
spraintarget_names = ["no", "yes"]

In [107]:
spraindata = df.drop(["Strains/Sprains_y_True", "Dislocations_y_True", "Arm Fractures_y_True", "Leg Fractures_y_True"], axis=1)
feature_names = spraindata.columns
spraindata.head()

   Position        BMI
0         0  24.391892
1         1  25.188615
2         2  26.660470
3         3  22.528441
4         2  26.532153

In [108]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, spraintarget, random_state=42)

In [109]:
from sklearn.ensemble import RandomForestClassifier
sprainrf = RandomForestClassifier(n_estimators=200)
sprainrf = sprainrf.fit(X_train, y_train)
sprainrf.score(X_test, y_test)

0.7661290322580645

In [110]:
sorted(zip(sprainrf.feature_importances_, feature_names), reverse=True)

[(0.9332754706032561, 'BMI'), (0.06672452939674385, 'Position')]

In [111]:
distarget = df["Dislocations_y_True"]
distarget_names = ["no", "yes"]

In [112]:
# disdata = df.drop(["Strains/Sprains_y_True", "Dislocations_y_True", "Arm Fractures_y_True", "Leg Fractures_y_True"], axis=1)
# feature_names = disdata.columns
# disdata.head()

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, distarget, random_state=42)

In [114]:
from sklearn.ensemble import RandomForestClassifier
disrf = RandomForestClassifier(n_estimators=200)
disrf = disrf.fit(X_train, y_train)
disrf.score(X_test, y_test)

0.9919354838709677

In [115]:
sorted(zip(disrf.feature_importances_, feature_names), reverse=True)

[(0.0, 'Position'), (0.0, 'BMI')]

In [116]:
y_test

454    0
73     0
310    0
175    0
332    0
      ..
220    0
412    0
405    0
321    0
22     0
Name: Dislocations_y_True, Length: 124, dtype: int64

In [117]:
df[df.Dislocations_y_True > 0].sum()

Position                   1.000000
BMI                       23.911565
Strains/Sprains_y_True     0.000000
Dislocations_y_True        6.000000
Arm Fractures_y_True       0.000000
Leg Fractures_y_True       0.000000
dtype: float64

In [118]:
armtarget = df["Arm Fractures_y_True"]
armtarget_names = ["no", "yes"]

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, armtarget, random_state=42)

In [120]:
from sklearn.ensemble import RandomForestClassifier
armrf = RandomForestClassifier(n_estimators=200)
armrf = armrf.fit(X_train, y_train)
armrf.score(X_test, y_test)

0.9919354838709677

In [121]:
sorted(zip(armrf.feature_importances_, feature_names), reverse=True)

[(0.9897612607889856, 'BMI'), (0.01023873921101445, 'Position')]

In [122]:
legtarget = df["Leg Fractures_y_True"]
legtarget_names = ["no", "yes"]

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, legtarget, random_state=42)

In [124]:
from sklearn.ensemble import RandomForestClassifier
legrf = RandomForestClassifier(n_estimators=200)
legrf = legrf.fit(X_train, y_train)
legrf.score(X_test, y_test)

1.0

In [125]:
sorted(zip(legrf.feature_importances_, feature_names), reverse=True)

[(0.8377354999646327, 'BMI'), (0.1622645000353673, 'Position')]

In [126]:
df = pd.read_csv('rookies-cleanest2.csv')
df.head()

  position        BMI   Height-1  HEIGHT  WEIGHT Team name
0        F  31.990386      6' 7"      79     284  Pelicans
1        G  24.425367   6' 4.5''      77     206    Lakers
2        G  22.765390   6' 4.5''      77     192      Heat
3        F  27.597340  6' 7.25''      79     245   Nuggets
4        G  23.611842  6' 4.25''      76     194      Suns

In [127]:
pos_labels = {}
for idx, row in df.iterrows():
    if row["position"] not in pos_labels:
        pos_labels[row["position"]] = len(pos_labels)
print(pos_labels)

{'F': 0, 'G': 1, 'G-F': 2, 'C': 3}

In [128]:
for pos in pos_labels:
    df.replace(pos, pos_labels[pos], inplace=True)
df.head(20)

    position        BMI   Height-1  HEIGHT  WEIGHT Team name
0          0  31.990386      6' 7"      79     284  Pelicans
1          1  24.425367   6' 4.5''      77     206    Lakers
2          1  22.765390   6' 4.5''      77     192      Heat
3          0  27.597340  6' 7.25''      79     245   Nuggets
4          1  23.611842  6' 4.25''      76     194      Suns
5          1  23.324846   5' 9.5''      72     172   Celtics
6          1  23.995733     6' 3''      75     192   Raptors
7          2  24.306797  6' 4.75''      77     205  Clippers
8          1  29.369778   6' 2.5''      75     235    Lakers
9          3  25.649160  7' 5.25''      89     289   Celtics
10         1  24.409722  5' 11.5''      72     180   Rockets
11         1  25.611064   6' 4.5''      77     216   Celtics
12         0  22.866368      6' 7"      79     203    Knicks
13         1  25.870400     6' 3''      75     207     Spurs
14         0  25.907707   6' 6.5''      79     230   Hornets
15         0  22.866368     6' 7''      79     203   Raptors
16         3  22.687537    6' 10''      82     217      Nets
17         1  24.828947  6' 4.25''      76     204  Pelicans
18         0  26.559622   6' 4.5''      77     224   Blazers
19         3  23.060346  7' 1.25''      85     237   Blazers

In [129]:
data = df.values
X = data[:, 0:2]
y = data[:, 2:5]

In [130]:
droppeddf=df.drop(columns=["Height-1", "HEIGHT", "WEIGHT", "Team name"])

In [131]:
print(X)

[[0 31.99038616]
 [1 24.42536684]
 [1 22.76539045]
 [0 27.59734017]
 [1 23.61184211]
 [1 23.32484568]
 [1 23.99573333]
 [2 24.3067971]
 [1 29.36977778]
 [3 25.64916046]
 [1 24.40972222]
 [1 25.61106426]
 [0 22.86636757]
 [1 25.8704]
 [0 25.907707100000003]
 [0 22.86636757]
 [3 22.68753718]
 [1 24.82894737]
 [0 26.5596222]
 [3 23.06034602]
 [1 25.07236842]
 [0 27.42996494]
 [0 23.35823916]
 [0 23.73304581]
 [1 27.74506667]
 [1 22.78240741]
 [1 23.87746294]
 [1 25.92434211]
 [1 25.61106426]
 [0 23.654863]
 [1 23.24671053]
 [1 22.97972973]
 [1 25.24551111]
 [0 22.89663891]
 [1 23.00252994]
 [1 24.24632653]
 [0 21.09]
 [1 23.12088889]
 [0 23.99278962]
 [1 21.74613333]
 [0 24.10543182]
 [0 25.53632479]
 [0 27.73175542]
 [0 29.34944116]
 [0 22.64760026]
 [3 24.96555403]
 [0 25.34449607]
 [1 22.33783784]
 [0 22.8475]
 [0 25.50129553]
 [0 26.28947368]
 [1 22.76539045]
 [1 23.24671053]
 [0 25.2640625]
 [1 27.75183495]
 [0 23.42957859]
 [1 23.09165198]
 [3 25.39414723]
 [0 23.10979619]
 [0 23.31693639]
 [3 20.72335601]
 [0 29.33223684]]

In [132]:
sprainrf.predict(droppeddf)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,
        0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int64)

In [133]:
disrf.predict(droppeddf)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [134]:
armrf.predict(droppeddf)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [135]:
legrf.predict(droppeddf)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [137]:
pip install pydot

Collecting pydot
  Downloading https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyparsing>=2.1.4 in c:\users\kmw58\.virtualenvs\21-machine-learning-q0o0v-9c\lib\site-packages (from pydot) (2.4.2)
Installing collected packages: pydot
Successfully installed pydot-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [139]:
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = sprainrf.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = ["position", "BMI"], rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')